---
  AWSTemplateFormatVersion: '2010-09-09'
  
  Parameters:
    EKSClusterName:
      Type: String
      Default: EKS
      Description: The desired name of your AWS EKS Cluster.
    
    EKSVersion:
      Type: String
      Default: 1.18
      AllowedValues: 
        - 1.16
        - 1.17
        - 1.18
      Description: The desired version of your AWS EKS Cluster.
    
    EKSNodeGroupName:
      Type: String
      Default: NodeGroup01
      Description: The desired name of your AWS EKS Node Group.
    
    EKSDesiredWorkerNode:
      Type: Number
      Default: 2
      Description: Number of desired Worker Node.
      MinValue: 1
      MaxValue: 7
  
    EKSWorkerNodeInstanceType:
      Type: String
      Default: t2.micro
      AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
        t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
        m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
        c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
        g3.8xlarge,r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
        i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
        d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
      ConstraintDescription: Must be a valid EC2 instance type
      Description: EC2 instance type for the node instances.
  
    EKSIAMRoleName:
      Type: String
      Default: EKSClusterRole
      Description: The name of the IAM role for the EKS service to assume.
    
    EKSKeyPair:
      Type: "AWS::EC2::KeyPair::KeyName"
      Default: "my-eks-key"
      Description: The name of Key Pair to etasblish connection with Worker Node.

  Resources:
    eksCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: !Ref EKSClusterName
        Version: !Ref EKSVersion
        RoleArn:
          "Fn::GetAtt": ["eksIAMRole", "Arn"]
        ResourcesVpcConfig:
          SecurityGroupIds:
            - !Ref eksSecurityGroup
          SubnetIds:
            - !Ref eksPublicSubnet01
            - !Ref eksPublicSubnet02
      DependsOn: [eksIAMRole, eksPublicSubnet01, eksPublicSubnet02, eksSecurityGroup]
  
    eksNodeGroup:
      Type: AWS::EKS::Nodegroup
      Properties:
        ClusterName: !Ref EKSClusterName
        NodeRole: 
          "Fn::GetAtt": ["eksNodeInstanceRole", "Arn"]
        AmiType: AL2_x86_64
        InstanceTypes: 
          - !Ref EKSWorkerNodeInstanceType
        NodegroupName: !Ref EKSNodeGroupName
        RemoteAccess:
          Ec2SshKey: !Ref EKSKeyPair
        ScalingConfig:
          MinSize: 1
          DesiredSize: !Ref EKSDesiredWorkerNode
          MaxSize: 7
        Labels:
          Project: aws-eks
        Subnets:
          - !Ref eksPublicSubnet01
          - !Ref eksPublicSubnet02
      DependsOn: [eksCluster, eksNodeInstanceRole]
  
  Outputs:
    SubnetIds:
      Description: Subnets IDs in the eksVPC
      Value: !Join [ ",", [ !Ref eksPublicSubnet01, !Ref eksPublicSubnet02 ] ]
    SecurityGroups:
      Description: Security group for the cluster control plane communication with worker nodes
      Value: !Join [ ",", [ !Ref eksSecurityGroup ] ]



