---
  AWSTemplateFormatVersion: '2010-09-09'
  Metadata:
    QSLint:
      Exclusions: [W9002, W9003, W9004, W9006]
  Parameters:
    EKSClusterName:
      Type: String
      Default: EKS
      Description: The desired name of your AWS EKS Cluster.
    
    EKSVersion:
      Type: String
      Default: 1.18
      AllowedValues: 
        - 1.16
        - 1.17
        - 1.18
      Description: The desired version of your AWS EKS Cluster.
    
    EKSNodeGroupName:
      Type: String
      Default: NodeGroup01
      Description: The desired name of your AWS EKS Node Group.
    
    EKSDesiredWorkerNode:
      Type: Number
      Default: 2
      Description: Number of desired Worker Node.
      MinValue: 1
      MaxValue: 7
  
    EKSWorkerNodeInstanceType:
      Type: String
      Default: t2.micro
      AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
        t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
        m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
        c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
        g3.8xlarge,r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
        i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
        d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
      ConstraintDescription: Must be a valid EC2 instance type
      Description: EC2 instance type for the node instances.
  
    EKSIAMRoleName:
      Type: String
      Default: "arn:aws:iam::680763698946:role/eks-cluster"
      Description: The name of the IAM role for the EKS service to assume.
    
    EKSKeyPair:
      Type: String
      Default: "my-eks-key"
      Description: The name of Key Pair to etasblish connection with Worker Node.
    
    Subnet1: 
         Type: String 
         Default: "subnet-0c45b1f5ee2ce5013" 
         Description: "First Private Subnet" 

    Subnet2: 
         Type: String 
         Default: "subnet-0c12dd4bd533213a7" 
         Description: "Second Private Subnet" 

    Subnet3: 
         Type: String 
         Default: "subnet-751ca67b" 
         Description: "Third Private Subnet" 

    eksSecurityGroup1: 
         Type: String 
         Default: "sg-0160c3568280889ad" 
         Description: "SecurityGroups" 

    eksSecurityGroup2: 
         Type: String 
         Default: "sg-030992e75f8a99e86" 
         Description: "SecurityGroups" 

    eksSecurityGroup3: 
          Type: String 
          Default: "sg-05252192c90b9f732" 
          Description: "SecurityGroups" 

    eksNodeInstanceRole: 
         Type: String 
         Default: "arn:ans:iam::acct_no:role/NodeInstanceRole" 
         Description: "IAM Role for EKS Nodes" 

    EKSPublicAccessEndpoint:
         Type: String
         AllowedValues: [Enabled, Disabled]
         Default: Disabled

    EKSPrivateAccessEndpoint:
         Type: String
         AllowedValues: [Enabled, Disabled]
         Default: Enabled 

  Conditions:
        EnablePrivateEndpoint: !Equals [ !Ref EKSPrivateAccessEndpoint, "Enabled" ]
        EnablePublicEndpoint: !Equals [ !Ref EKSPublicAccessEndpoint, "Enabled" ]

  Resources: 
    EKS: 
      Type: "AWSQS::EKS::Cluster" 
      Properties: 
        Name: !Ref EKSClusterName 
        Version: !Ref EKSVersion 
        RoleArn: !Ref EKSIAMRoleName 
        ResourcesVpcConfig: 
          SecurityGroupids: 
            - !Ref eksSecurityGroup1 
            - !Ref eksSecurityGroup2 
            - !Ref eksSecurityGroup3 
          Subnetlds: 
            - !Ref Subnet1 
            - !Ref Subnet2 
            - !Ref Subnet3
          EndpointPrivateAccess: !If [ EnablePrivateEndpoint, true, false ]
          EndpointPublicAccess: !If [ EnablePublicEndpoint, true, false ]

    eksNodeGroup: 
      Type: AWS::EKS::Nodegroup 
      Properties: 
        CapacityType: ON_DEMAND 
        ClusterName: !Ref EKSClusterName 
        NodeRole: 
          !Ref eksNodeInstanceRole 
        AmiType: AL2_x86_64 
        InstanceTypes: 
          - !Ref EKSWorkerNodeInstanceType 
        NodegroupName: !Ref EKSNodeGroupName 
        RemoteAccess: 
          Ec2SshKey: !Ref EKSKeyPair 
          SourceSecurityGroups: 
            - !Ref eksSecurityGroup1 
            - !Ref eksSecurityGroup2 
            - !Ref eksSecurityGroup3 
        ScalingConfig: 
          MinSize: 1 
          DesiredSize: !Ref EKSDesiredWorkerNode 
          MaxSize: 7 
        Subnets: 
          - !Ref Subnet1 
          - !Ref Subnet2 
          - !Ref Subnet3 
      DependsOn: [EKS]




