---
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH

Resources:
  myStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        https://s3.us-west-1.amazonaws.com/cloudformation-templates-us-west-1/LAMP_Single_Instance.template
      Parameters:
        KeyName: !Ref SSHKey
        DBName: "mydb"
        DBUser: "user"
        DBPassword: "pass"
        DBRootPassword: "passroot"
        InstanceType: t2.micro
        SSHLocation: "0.0.0.0/0"

Outputs:
  StackRef:
    Value: !Ref myStack
  OutputFromNestedStack:
    Value: !GetAtt myStack.Outputs.WebsiteURL
